version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports: 
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    networks:
      - pizza-delivery
    env_file: .env
  
  users_mongodb:
    image: mongo
    container_name: 'Users_DB'
    ports:
      - '27018:27017'
    volumes:
      - users-mongodb:/data/db
      - users-mongodb_config:/data/configdb
    networks:
      - pizza-delivery
    env_file: .env

  products_mongodb:
    image: mongo
    container_name: 'Products_DB'
    ports: 
      - '27017:27017'
    volumes:
      - products-mongodb:/data/db
      - products-mongodb_config:/data/configdb
    networks:
      - pizza-delivery
    env_file: .env

  mongo-express:
    image: mongo-express:latest
    container_name: 'Mongo_UI'
    depends_on:
      - users_mongodb
    ports:
      - '4000:8081'
    restart: unless-stopped
    networks:
      - pizza-delivery
    env_file: .env
  
  auth_service:
    container_name: 'Auth'
    build: 
      context: './auth'
    ports:
      - '3002:3002'
    networks:
      - pizza-delivery
    depends_on:
      - 'rabbitmq'
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run start'
    env_file: .env

  products_service:
    container_name: 'Products'
    build: 
      context: './products'
    ports:
      - '3001:3001'
    volumes:
      - products-service:/usr/src/app
    depends_on:
      - products_mongodb
    networks:
      - pizza-delivery
    env_file: .env

  users_service:
    container_name: "Users"
    build:
      context: './users'
    ports:
      - '3003:3003'
    depends_on:
      - 'users_mongodb'
      - 'rabbitmq'
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run start'
    networks:
      - pizza-delivery
    env_file: .env

volumes:
  products-service:
  products-mongodb:
  users-mongodb:
  products-mongodb_config:
  users-mongodb_config:
  rabbitmq-data:
  rabbitmq-logs:
networks:
  pizza-delivery:
    driver: bridge