version: '3'
services:
  products-api:
    build: 
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - pizza_delivery
    env_file:
      - .env
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - pizza_delivery
    env_file:
      - .env
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 3001:8081
    restart: unless-stopped
    networks:
      - pizza_delivery
    env_file:
      - .env
volumes:
  mongodb:
  mongodb_config:
networks:
  pizza_delivery: